version: '3'
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

networks:
  spark-network:
    driver: bridge

services:
  jupyterlab:
    image: andreper/jupyterlab:3.0.0-spark-3.0.0
    container_name: jupyterlab
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - "/mnt/d/TestChatBotAPIWITHSpark:/opt/workspace"
    networks:
      - spark-network
    environment:
    command: >
      bash -c "apt update && apt install -y openjdk-11-jdk git cmake build-essential && jupyter lab --ip=0.0.0.0 --allow-root"

  spark-master:
    image: andreper/spark-master:3.0.0
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - "/mnt/d/TestChatBotAPIWITHSpark:/opt/workspace"
    networks:
      - spark-network
    environment:

    command: >
      bash -c "apt update && apt install -y openjdk-11-jdk git cmake build-essential && tail -f /dev/null"

  spark-worker-1:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=5g
      - SPARK_MASTER_URL=spark://spark-master:7077

    ports:
      - "8081:8081"
    volumes:
      - "/mnt/d/TestChatBotAPIWITHSpark:/opt/workspace"
    depends_on:
      - spark-master
    networks:
      - spark-network
    command: >
      bash -c "apt update && apt install -y openjdk-11-jdk git cmake build-essential && tail -f /dev/null"

  spark-worker-2:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=5g
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8082:8082"
    volumes:
      - "/mnt/d/TestChatBotAPIWITHSpark:/opt/workspace"
    depends_on:
      - spark-master
    networks:
      - spark-network
    command: >
      bash -c "apt update && apt install -y openjdk-11-jdk git cmake build-essential && tail -f /dev/null"
